In [22]:
import os
import sys
import pandas as pd
import csv
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
# Add project path to sys.path
ROOT_DIR = os.path.abspath('..')
if ROOT_DIR not in sys.path:
    sys.path.append(ROOT_DIR)
    
# Get DATA_DIR from project utils module
from utils import DATA_PATH

# Get petfinder files
petfinder_fnames = list()
for fname in os.listdir(DATA_PATH):
    if 'petfinder' in fname:
        petfinder_fnames.append(fname)
        
petfinder_fnames

['petfinder_texas_05052019.csv',
 'petfinder_texas_04292019.csv',
 'petfinder_texas_05032019.csv',
 'petfinder_texas_04302019.csv',
 'petfinder_texas_05062019.csv',
 'petfinder_texas_05082019.csv',
 'petfinder_texas_04212019.csv',
 'petfinder_texas_05012019.csv',
 'petfinder_texas_05072019.csv',
 'petfinder_texas_05022019.csv',
 'petfinder_texas_04282019.csv']

In [16]:
# Initialize dataframe
df = pd.read_csv(os.path.join(DATA_PATH, petfinder_fnames[0]))
df.tail()

,type,status,colors_secondary,url,species,breeds_unknown,id,name,attributes_shots_current,breeds_primary,...,published_at,organization_id,attributes_spayed_neutered,environment_dogs,environment_children,attributes_house_trained,colors_tertiary,age,attributes_declawed,size
18190,Cat,adopted,NaN,https://www.petfinder.com/cat/bestet-1893447/t...,Cat,False,1893447,Bestet,False,Tortoiseshell,...,2003-07-19T00:00:00+0000,TX229,True,NaN,NaN,False,NaN,Adult,False,Medium
18191,Cat,adopted,NaN,https://www.petfinder.com/cat/madison-1754798/...,Cat,False,1754798,Madison,False,Domestic Short Hair,...,2003-06-04T00:00:00+0000,TX229,False,NaN,False,False,NaN,Adult,False,Medium
18192,Dog,adopted,NaN,https://www.petfinder.com/dog/ranger-1036041/t...,Dog,False,1036041,Ranger,True,Shepherd,...,2002-11-14T00:00:00+0000,TX229,True,NaN,NaN,False,NaN,Adult,NaN,Large
18193,Dog,adopted,NaN,https://www.petfinder.com/dog/maverick-832254/...,Dog,False,832254,Maverick,True,German Shepherd Dog,...,2002-05-20T00:00:00+0000,TX229,True,NaN,NaN,True,NaN,Adult,NaN,Large
18194,Dog,adopted,NaN,https://www.petfinder.com/dog/sissy-751960/tx/...,Dog,False,751960,Sissy,True,Shepherd,...,2002-04-03T00:00:00+0000,TX229,True,NaN,NaN,False,NaN,Adult,NaN,Medium

In [20]:
# Load all petfinder csv into single dataframe
for i, fname in enumerate(petfinder_fnames):
    time_stamp = fname.split('.csv')[0].split('_')[-1]
    if i == 0:
        df['time_stamp'] = time_stamp
        print(df.tail())
        continue
    
    temp_df = pd.read_csv(os.path.join(DATA_PATH, fname))
    temp_df['time_stamp'] = time_stamp
    df = df.append(temp_df, ignore_index=True)
    print(df.tail())

         age attributes_declawed  attributes_house_trained  \
18154  Adult               False                     False
18155  Adult               False                     False
18156  Adult                 NaN                     False
18157  Adult                 NaN                      True
18158  Adult                 NaN                     False

       attributes_shots_current  attributes_spayed_neutered  \
18154                     False                        True
18155                     False                       False
18156                      True                        True
18157                      True                        True
18158                      True                        True

       attributes_special_needs  breeds_mixed       breeds_primary  \
18154                     False          True        Tortoiseshell
18155                      True          True  Domestic Short Hair
18156                     False          True             Shepherd
18157                     False          True  German Shepherd Dog
18158                     False          True             Shepherd

      breeds_secondary  breeds_unknown  ...       id      name  \
18154              NaN           False  ...  1893447    Bestet
18155              NaN           False  ...  1754798   Madison
18156              NaN           False  ...  1036041    Ranger
18157              NaN           False  ...   832254  Maverick
18158              NaN           False  ...   751960     Sissy

      organization_id              published_at    size species   status  \
18154           TX229  2003-07-19T00:00:00+0000  Medium     Cat  adopted
18155           TX229  2003-06-04T00:00:00+0000  Medium     Cat  adopted
18156           TX229  2002-11-14T00:00:00+0000   Large     Dog  adopted
18157           TX229  2002-05-20T00:00:00+0000   Large     Dog  adopted
18158           TX229  2002-04-03T00:00:00+0000  Medium     Dog  adopted

      time_stamp type                                                url
18154   05052019  Cat  https://www.petfinder.com/cat/bestet-1893447/t...
18155   05052019  Cat  https://www.petfinder.com/cat/madison-1754798/...
18156   05052019  Dog  https://www.petfinder.com/dog/ranger-1036041/t...
18157   05052019  Dog  https://www.petfinder.com/dog/maverick-832254/...
18158   05052019  Dog  https://www.petfinder.com/dog/sissy-751960/tx/...

[5 rows x 29 columns]

/home/johnny/civic-projects/saveallthepets/env/lib/python3.6/site-packages/pandas/core/frame.py:6692: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

          age attributes_declawed  attributes_house_trained  \
217514  Adult               False                     False
217515  Adult               False                     False
217516  Adult                 NaN                     False
217517  Adult                 NaN                      True
217518  Adult                 NaN                     False

        attributes_shots_current  attributes_spayed_neutered  \
217514                     False                        True
217515                     False                       False
217516                      True                        True
217517                      True                        True
217518                      True                        True

        attributes_special_needs  breeds_mixed       breeds_primary  \
217514                     False          True        Tortoiseshell
217515                      True          True  Domestic Short Hair
217516                     False          True             Shepherd
217517                     False          True  German Shepherd Dog
217518                     False          True             Shepherd

       breeds_secondary  breeds_unknown  ...       id      name  \
217514              NaN           False  ...  1893447    Bestet
217515              NaN           False  ...  1754798   Madison
217516              NaN           False  ...  1036041    Ranger
217517              NaN           False  ...   832254  Maverick
217518              NaN           False  ...   751960     Sissy

       organization_id              published_at    size species   status  \
217514           TX229  2003-07-19T00:00:00+0000  Medium     Cat  adopted
217515           TX229  2003-06-04T00:00:00+0000  Medium     Cat  adopted
217516           TX229  2002-11-14T00:00:00+0000   Large     Dog  adopted
217517           TX229  2002-05-20T00:00:00+0000   Large     Dog  adopted
217518           TX229  2002-04-03T00:00:00+0000  Medium     Dog  adopted

       time_stamp type                                                url
217514   04292019  Cat  https://www.petfinder.com/cat/bestet-1893447/t...
217515   04292019  Cat  https://www.petfinder.com/cat/madison-1754798/...
217516   04292019  Dog  https://www.petfinder.com/dog/ranger-1036041/t...
217517   04292019  Dog  https://www.petfinder.com/dog/maverick-832254/...
217518   04292019  Dog  https://www.petfinder.com/dog/sissy-751960/tx/...

[5 rows x 29 columns]
          age attributes_declawed  attributes_house_trained  \
235713  Adult               False                     False
235714  Adult               False                     False
235715  Adult                 NaN                     False
235716  Adult                 NaN                      True
235717  Adult                 NaN                     False

        attributes_shots_current  attributes_spayed_neutered  \
235713                     False                        True
235714                     False                       False
235715                      True                        True
235716                      True                        True
235717                      True                        True

        attributes_special_needs  breeds_mixed       breeds_primary  \
235713                     False          True        Tortoiseshell
235714                      True          True  Domestic Short Hair
235715                     False          True             Shepherd
235716                     False          True  German Shepherd Dog
235717                     False          True             Shepherd

       breeds_secondary  breeds_unknown  ...       id      name  \
235713              NaN           False  ...  1893447    Bestet
235714              NaN           False  ...  1754798   Madison
235715              NaN           False  ...  1036041    Ranger
235716              NaN           False  ...   832254  Maverick
235717              NaN           False  ...   751960     Sissy

       organization_id              published_at    size species   status  \
235713           TX229  2003-07-19T00:00:00+0000  Medium     Cat  adopted
235714           TX229  2003-06-04T00:00:00+0000  Medium     Cat  adopted
235715           TX229  2002-11-14T00:00:00+0000   Large     Dog  adopted
235716           TX229  2002-05-20T00:00:00+0000   Large     Dog  adopted
235717           TX229  2002-04-03T00:00:00+0000  Medium     Dog  adopted

       time_stamp type                                                url
235713   05032019  Cat  https://www.petfinder.com/cat/bestet-1893447/t...
235714   05032019  Cat  https://www.petfinder.com/cat/madison-1754798/...
235715   05032019  Dog  https://www.petfinder.com/dog/ranger-1036041/t...
235716   05032019  Dog  https://www.petfinder.com/dog/maverick-832254/...
235717   05032019  Dog  https://www.petfinder.com/dog/sissy-751960/tx/...

[5 rows x 29 columns]
          age attributes_declawed  attributes_house_trained  \
253872  Adult               False                     False
253873  Adult               False                     False
253874  Adult                 NaN                     False
253875  Adult                 NaN                      True
253876  Adult                 NaN                     False

        attributes_shots_current  attributes_spayed_neutered  \
253872                     False                        True
253873                     False                       False
253874                      True                        True
253875                      True                        True
253876                      True                        True

        attributes_special_needs  breeds_mixed       breeds_primary  \
253872                     False          True        Tortoiseshell
253873                      True          True  Domestic Short Hair
253874                     False          True             Shepherd
253875                     False          True  German Shepherd Dog
253876                     False          True             Shepherd

       breeds_secondary  breeds_unknown  ...       id      name  \
253872              NaN           False  ...  1893447    Bestet
253873              NaN           False  ...  1754798   Madison
253874              NaN           False  ...  1036041    Ranger
253875              NaN           False  ...   832254  Maverick
253876              NaN           False  ...   751960     Sissy

       organization_id              published_at    size species   status  \
253872           TX229  2003-07-19T00:00:00+0000  Medium     Cat  adopted
253873           TX229  2003-06-04T00:00:00+0000  Medium     Cat  adopted
253874           TX229  2002-11-14T00:00:00+0000   Large     Dog  adopted
253875           TX229  2002-05-20T00:00:00+0000   Large     Dog  adopted
253876           TX229  2002-04-03T00:00:00+0000  Medium     Dog  adopted

       time_stamp type                                                url
253872   04302019  Cat  https://www.petfinder.com/cat/bestet-1893447/t...
253873   04302019  Cat  https://www.petfinder.com/cat/madison-1754798/...
253874   04302019  Dog  https://www.petfinder.com/dog/ranger-1036041/t...
253875   04302019  Dog  https://www.petfinder.com/dog/maverick-832254/...
253876   04302019  Dog  https://www.petfinder.com/dog/sissy-751960/tx/...

[5 rows x 29 columns]
          age attributes_declawed  attributes_house_trained  \
271840  Adult               False                     False
271841  Adult               False                     False
271842  Adult                 NaN                     False
271843  Adult                 NaN                      True
271844  Adult                 NaN                     False

        attributes_shots_current  attributes_spayed_neutered  \
271840                     False                        True
271841                     False                       False
271842                      True                        True
271843                      True                        True
271844                      True                        True

        attributes_special_needs  breeds_mixed       breeds_primary  \
271840                     False          True        Tortoiseshell
271841                      True          True  Domestic Short Hair
271842                     False          True             Shepherd
271843                     False          True  German Shepherd Dog
271844                     False          True             Shepherd

       breeds_secondary  breeds_unknown  ...       id      name  \
271840              NaN           False  ...  1893447    Bestet
271841              NaN           False  ...  1754798   Madison
271842              NaN           False  ...  1036041    Ranger
271843              NaN           False  ...   832254  Maverick
271844              NaN           False  ...   751960     Sissy

       organization_id              published_at    size species   status  \
271840           TX229  2003-07-19T00:00:00+0000  Medium     Cat  adopted
271841           TX229  2003-06-04T00:00:00+0000  Medium     Cat  adopted
271842           TX229  2002-11-14T00:00:00+0000   Large     Dog  adopted
271843           TX229  2002-05-20T00:00:00+0000   Large     Dog  adopted
271844           TX229  2002-04-03T00:00:00+0000  Medium     Dog  adopted

       time_stamp type                                                url
271840   05062019  Cat  https://www.petfinder.com/cat/bestet-1893447/t...
271841   05062019  Cat  https://www.petfinder.com/cat/madison-1754798/...
271842   05062019  Dog  https://www.petfinder.com/dog/ranger-1036041/t...
271843   05062019  Dog  https://www.petfinder.com/dog/maverick-832254/...
271844   05062019  Dog  https://www.petfinder.com/dog/sissy-751960/tx/...

[5 rows x 29 columns]

          age attributes_declawed  attributes_house_trained  \
289863  Adult               False                     False
289864  Adult               False                     False
289865  Adult                 NaN                     False
289866  Adult                 NaN                      True
289867  Adult                 NaN                     False

        attributes_shots_current  attributes_spayed_neutered  \
289863                     False                        True
289864                     False                       False
289865                      True                        True
289866                      True                        True
289867                      True                        True

        attributes_special_needs  breeds_mixed       breeds_primary  \
289863                     False          True        Tortoiseshell
289864                      True          True  Domestic Short Hair
289865                     False          True             Shepherd
289866                     False          True  German Shepherd Dog
289867                     False          True             Shepherd

       breeds_secondary  breeds_unknown  ...       id      name  \
289863              NaN           False  ...  1893447    Bestet
289864              NaN           False  ...  1754798   Madison
289865              NaN           False  ...  1036041    Ranger
289866              NaN           False  ...   832254  Maverick
289867              NaN           False  ...   751960     Sissy

       organization_id              published_at    size species   status  \
289863           TX229  2003-07-19T00:00:00+0000  Medium     Cat  adopted
289864           TX229  2003-06-04T00:00:00+0000  Medium     Cat  adopted
289865           TX229  2002-11-14T00:00:00+0000   Large     Dog  adopted
289866           TX229  2002-05-20T00:00:00+0000   Large     Dog  adopted
289867           TX229  2002-04-03T00:00:00+0000  Medium     Dog  adopted

       time_stamp type                                                url
289863   05082019  Cat  https://www.petfinder.com/cat/bestet-1893447/t...
289864   05082019  Cat  https://www.petfinder.com/cat/madison-1754798/...
289865   05082019  Dog  https://www.petfinder.com/dog/ranger-1036041/t...
289866   05082019  Dog  https://www.petfinder.com/dog/maverick-832254/...
289867   05082019  Dog  https://www.petfinder.com/dog/sissy-751960/tx/...

[5 rows x 29 columns]
          age attributes_declawed  attributes_house_trained  \
307985  Adult               False                     False
307986  Adult               False                     False
307987  Adult                 NaN                     False
307988  Adult                 NaN                      True
307989  Adult                 NaN                     False

        attributes_shots_current  attributes_spayed_neutered  \
307985                     False                        True
307986                     False                       False
307987                      True                        True
307988                      True                        True
307989                      True                        True

        attributes_special_needs  breeds_mixed       breeds_primary  \
307985                     False          True        Tortoiseshell
307986                      True          True  Domestic Short Hair
307987                     False          True             Shepherd
307988                     False          True  German Shepherd Dog
307989                     False          True             Shepherd

       breeds_secondary  breeds_unknown  ...       id      name  \
307985              NaN           False  ...  1893447    Bestet
307986              NaN           False  ...  1754798   Madison
307987              NaN           False  ...  1036041    Ranger
307988              NaN           False  ...   832254  Maverick
307989              NaN           False  ...   751960     Sissy

       organization_id              published_at    size species   status  \
307985           TX229  2003-07-19T00:00:00+0000  Medium     Cat  adopted
307986           TX229  2003-06-04T00:00:00+0000  Medium     Cat  adopted
307987           TX229  2002-11-14T00:00:00+0000   Large     Dog  adopted
307988           TX229  2002-05-20T00:00:00+0000   Large     Dog  adopted
307989           TX229  2002-04-03T00:00:00+0000  Medium     Dog  adopted

       time_stamp type                                                url
307985   04212019  Cat  https://www.petfinder.com/cat/bestet-1893447/t...
307986   04212019  Cat  https://www.petfinder.com/cat/madison-1754798/...
307987   04212019  Dog  https://www.petfinder.com/dog/ranger-1036041/t...
307988   04212019  Dog  https://www.petfinder.com/dog/maverick-832254/...
307989   04212019  Dog  https://www.petfinder.com/dog/sissy-751960/tx/...

[5 rows x 29 columns]
          age attributes_declawed  attributes_house_trained  \
326169  Adult               False                     False
326170  Adult               False                     False
326171  Adult                 NaN                     False
326172  Adult                 NaN                      True
326173  Adult                 NaN                     False

        attributes_shots_current  attributes_spayed_neutered  \
326169                     False                        True
326170                     False                       False
326171                      True                        True
326172                      True                        True
326173                      True                        True

        attributes_special_needs  breeds_mixed       breeds_primary  \
326169                     False          True        Tortoiseshell
326170                      True          True  Domestic Short Hair
326171                     False          True             Shepherd
326172                     False          True  German Shepherd Dog
326173                     False          True             Shepherd

       breeds_secondary  breeds_unknown  ...       id      name  \
326169              NaN           False  ...  1893447    Bestet
326170              NaN           False  ...  1754798   Madison
326171              NaN           False  ...  1036041    Ranger
326172              NaN           False  ...   832254  Maverick
326173              NaN           False  ...   751960     Sissy

       organization_id              published_at    size species   status  \
326169           TX229  2003-07-19T00:00:00+0000  Medium     Cat  adopted
326170           TX229  2003-06-04T00:00:00+0000  Medium     Cat  adopted
326171           TX229  2002-11-14T00:00:00+0000   Large     Dog  adopted
326172           TX229  2002-05-20T00:00:00+0000   Large     Dog  adopted
326173           TX229  2002-04-03T00:00:00+0000  Medium     Dog  adopted

       time_stamp type                                                url
326169   05012019  Cat  https://www.petfinder.com/cat/bestet-1893447/t...
326170   05012019  Cat  https://www.petfinder.com/cat/madison-1754798/...
326171   05012019  Dog  https://www.petfinder.com/dog/ranger-1036041/t...
326172   05012019  Dog  https://www.petfinder.com/dog/maverick-832254/...
326173   05012019  Dog  https://www.petfinder.com/dog/sissy-751960/tx/...

[5 rows x 29 columns]
          age attributes_declawed  attributes_house_trained  \
344164  Adult               False                     False
344165  Adult               False                     False
344166  Adult                 NaN                     False
344167  Adult                 NaN                      True
344168  Adult                 NaN                     False

        attributes_shots_current  attributes_spayed_neutered  \
344164                     False                        True
344165                     False                       False
344166                      True                        True
344167                      True                        True
344168                      True                        True

        attributes_special_needs  breeds_mixed       breeds_primary  \
344164                     False          True        Tortoiseshell
344165                      True          True  Domestic Short Hair
344166                     False          True             Shepherd
344167                     False          True  German Shepherd Dog
344168                     False          True             Shepherd

       breeds_secondary  breeds_unknown  ...       id      name  \
344164              NaN           False  ...  1893447    Bestet
344165              NaN           False  ...  1754798   Madison
344166              NaN           False  ...  1036041    Ranger
344167              NaN           False  ...   832254  Maverick
344168              NaN           False  ...   751960     Sissy

       organization_id              published_at    size species   status  \
344164           TX229  2003-07-19T00:00:00+0000  Medium     Cat  adopted
344165           TX229  2003-06-04T00:00:00+0000  Medium     Cat  adopted
344166           TX229  2002-11-14T00:00:00+0000   Large     Dog  adopted
344167           TX229  2002-05-20T00:00:00+0000   Large     Dog  adopted
344168           TX229  2002-04-03T00:00:00+0000  Medium     Dog  adopted

       time_stamp type                                                url
344164   05072019  Cat  https://www.petfinder.com/cat/bestet-1893447/t...
344165   05072019  Cat  https://www.petfinder.com/cat/madison-1754798/...
344166   05072019  Dog  https://www.petfinder.com/dog/ranger-1036041/t...
344167   05072019  Dog  https://www.petfinder.com/dog/maverick-832254/...
344168   05072019  Dog  https://www.petfinder.com/dog/sissy-751960/tx/...

[5 rows x 29 columns]

          age attributes_declawed  attributes_house_trained  \
362353  Adult               False                     False
362354  Adult               False                     False
362355  Adult                 NaN                     False
362356  Adult                 NaN                      True
362357  Adult                 NaN                     False

        attributes_shots_current  attributes_spayed_neutered  \
362353                     False                        True
362354                     False                       False
362355                      True                        True
362356                      True                        True
362357                      True                        True

        attributes_special_needs  breeds_mixed       breeds_primary  \
362353                     False          True        Tortoiseshell
362354                      True          True  Domestic Short Hair
362355                     False          True             Shepherd
362356                     False          True  German Shepherd Dog
362357                     False          True             Shepherd

       breeds_secondary  breeds_unknown  ...       id      name  \
362353              NaN           False  ...  1893447    Bestet
362354              NaN           False  ...  1754798   Madison
362355              NaN           False  ...  1036041    Ranger
362356              NaN           False  ...   832254  Maverick
362357              NaN           False  ...   751960     Sissy

       organization_id              published_at    size species   status  \
362353           TX229  2003-07-19T00:00:00+0000  Medium     Cat  adopted
362354           TX229  2003-06-04T00:00:00+0000  Medium     Cat  adopted
362355           TX229  2002-11-14T00:00:00+0000   Large     Dog  adopted
362356           TX229  2002-05-20T00:00:00+0000   Large     Dog  adopted
362357           TX229  2002-04-03T00:00:00+0000  Medium     Dog  adopted

       time_stamp type                                                url
362353   05022019  Cat  https://www.petfinder.com/cat/bestet-1893447/t...
362354   05022019  Cat  https://www.petfinder.com/cat/madison-1754798/...
362355   05022019  Dog  https://www.petfinder.com/dog/ranger-1036041/t...
362356   05022019  Dog  https://www.petfinder.com/dog/maverick-832254/...
362357   05022019  Dog  https://www.petfinder.com/dog/sissy-751960/tx/...

[5 rows x 29 columns]
          age attributes_declawed  attributes_house_trained  \
380512  Adult               False                     False
380513  Adult               False                     False
380514  Adult                 NaN                     False
380515  Adult                 NaN                      True
380516  Adult                 NaN                     False

        attributes_shots_current  attributes_spayed_neutered  \
380512                     False                        True
380513                     False                       False
380514                      True                        True
380515                      True                        True
380516                      True                        True

        attributes_special_needs  breeds_mixed       breeds_primary  \
380512                     False          True        Tortoiseshell
380513                      True          True  Domestic Short Hair
380514                     False          True             Shepherd
380515                     False          True  German Shepherd Dog
380516                     False          True             Shepherd

       breeds_secondary  breeds_unknown  ...       id      name  \
380512              NaN           False  ...  1893447    Bestet
380513              NaN           False  ...  1754798   Madison
380514              NaN           False  ...  1036041    Ranger
380515              NaN           False  ...   832254  Maverick
380516              NaN           False  ...   751960     Sissy

       organization_id              published_at    size species   status  \
380512           TX229  2003-07-19T00:00:00+0000  Medium     Cat  adopted
380513           TX229  2003-06-04T00:00:00+0000  Medium     Cat  adopted
380514           TX229  2002-11-14T00:00:00+0000   Large     Dog  adopted
380515           TX229  2002-05-20T00:00:00+0000   Large     Dog  adopted
380516           TX229  2002-04-03T00:00:00+0000  Medium     Dog  adopted

       time_stamp type                                                url
380512   04282019  Cat  https://www.petfinder.com/cat/bestet-1893447/t...
380513   04282019  Cat  https://www.petfinder.com/cat/madison-1754798/...
380514   04282019  Dog  https://www.petfinder.com/dog/ranger-1036041/t...
380515   04282019  Dog  https://www.petfinder.com/dog/maverick-832254/...
380516   04282019  Dog  https://www.petfinder.com/dog/sissy-751960/tx/...

[5 rows x 29 columns]

In [21]:
df.columns

Index(['age', 'attributes_declawed', 'attributes_house_trained',
       'attributes_shots_current', 'attributes_spayed_neutered',
       'attributes_special_needs', 'breeds_mixed', 'breeds_primary',
       'breeds_secondary', 'breeds_unknown', 'coat', 'colors_primary',
       'colors_secondary', 'colors_tertiary', 'description',
       'environment_cats', 'environment_children', 'environment_dogs',
       'gender', 'id', 'name', 'organization_id', 'published_at', 'size',
       'species', 'status', 'time_stamp', 'type', 'url'],
      dtype='object')

In [30]:
unique_df = df.drop_duplicates(subset='id', keep='first')
unique_df.type.value_counts()

Dog              13868
Cat               4570
Small & Furry       48
Rabbit              36
Horse               13
Barnyard             7
Bird                 4
Name: type, dtype: int64

In [32]:
unique_df.species.value_counts()

Dog                13868
Cat                 4570
Rabbit                36
Guinea Pig            27
Horse                 10
Rat                    9
Ferret                 9
Goat                   5
Mouse                  3
Pot Bellied            2
Pony                   2
Duck                   1
Goose                  1
Chicken                1
Parakeet               1
Miniature Horse        1
Name: species, dtype: int64

In [46]:
group = df.groupby(['time_stamp', 'status'])
group['status'].count()

time_stamp  status
04212019    adoptable       857
            adopted       17264
            found             1
04282019    adoptable       856
            adopted       17302
            found             1
04292019    adoptable       849
            adopted       17313
            found             1
04302019    adoptable       848
            adopted       17310
            found             1
05012019    adoptable       865
            adopted       17318
            found             1
05022019    adoptable       861
            adopted       17327
            found             1
05032019    adoptable       865
            adopted       17333
            found             1
05052019    adoptable      9424
            adopted      189921
            found            11
05062019    adoptable       839
            adopted       17128
            found             1
05072019    adoptable       858
            adopted       17136
            found             1
05082019    adoptable       880
            adopted       17142
            found             1
Name: status, dtype: int64